#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

#cleanCase0
rm -r 0 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45
rm log.*


#------------------------------------------------------------------------------
