#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

#runApplication blockMesh

#runApplication postProcess -func writeCellCentres -time 0

#runApplication setFields

runApplication $(getApplication)

#------------------------------------------------------------------------------
