#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication createPatch -overwrite

restore0Dir

runApplication postProcess -func writeCellCentres -time 0

cp -r orig.1.5 1.5

runApplication $(getApplication)

#------------------------------------------------------------------------------
